# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: rigerc/rigerc.github.io
  branch: main
  identity_url: https://auth.decapbridge.com/sites/996479d6-dd09-4ff6-81dd-e6d326a0bff6
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://rigerc.github.io

media_folder: "site/public/uploads"
public_folder: "/uploads"

collections:
  - name: "reviews"
    label: "Reviews"
    label_singular: "Review"
    folder: site/src/content/reviews
    format: frontmatter
    create: true
    slug: "{{slug}}"
    preview_path: "/reviews/{{slug}}/"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        date_format: "YYYY-MM-DD"
      - { label: "Draft", name: "draft", widget: "boolean", required: false }
      - label: "Rating"
        name: "rating"
        widget: "number"
        min: 1
        max: 5
        step: 1
      - label: "Release Year"
        name: "release_year"
        widget: "number"
        required: false
      - label: "Related Link"
        name: "related_link"
        widget: "string"
        required: false
        hint: "Optional URL to related resource (album, IMDB, product page)."
      - label: "Categories"
        name: "categories"
        widget: "list"
        required: true
        field:
          label: "Category"
          name: "category"
          widget: "select"
          options:
            - film
            - music
            - book
            - dj
            - place
            - event
            - game
          hint: "Choose a single category (site expects an array with one item)."
      - label: "Body"
        name: "body"
        widget: "markdown"
