# Decap CMS configuration for the Astro "reviews" collection
# Paste this file at: site/public/admin/config.yml

backend:
  name: git-gateway

media_folder: "site/public/uploads"
public_folder: "/uploads"

collections:
  - name: "reviews"
    label: "Reviews"
    label_singular: "Review"
    folder: "site/src/content/reviews"
    create: true
    slug: "{{slug}}"
    preview_path: "/reviews/{{slug}}/"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        date_format: "YYYY-MM-DD"
      - { label: "Draft", name: "draft", widget: "boolean", required: false }
      - label: "Rating"
        name: "rating"
        widget: "number"
        min: 1
        max: 5
        step: 1
      - label: "Release Year"
        name: "release_year"
        widget: "number"
        required: false
      - label: "Related Link"
        name: "related_link"
        widget: "string"
        required: false
        hint: "Optional URL to related resource (album, IMDB, product page)."
      - label: "Categories"
        name: "categories"
        widget: "list"
        required: true
        field:
          label: "Category"
          name: "category"
          widget: "select"
          options:
            - film
            - music
            - book
            - dj
            - place
            - event
            - game
          hint: "Choose a single category (site expects an array with one item)."
      - label: "Body"
        name: "body"
        widget: "markdown"
